#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --name-only HEAD~1..HEAD -- | grep 'package.json'; then
  pnpm i
fi

if git diff --name-only HEAD~1..HEAD -- | grep 'schema.prisma'; then
  pnpm run postinstall
fi
